#!/usr/bin/env/bash

_native() {
  if [[ $(sysctl -n sysctl.proc_translated) -eq 1 ]]; then
    export ROSETTA_MODE=0
    # echo "Entering Native mode..."
    # exec /usr/bin/arch -arm64 /bin/zsh
  fi
}
_rosetta() {
  if [[ $(sysctl -n sysctl.proc_translated) -eq 0 ]]; then
    export ROSETTA_MODE=1
    # echo "Entering Rosetta mode..."
    # exec /usr/bin/arch -x86_64 /bin/zsh
  fi
}
_mamba() {
  if [ -n "$1" ]; then
    export CONDA_DEFAULT_ENV="$1"
  else
    (>&2 echo No environment specified);
    exit 1;
  fi;
}

layout_native() { _native; }
layout_rosetta() { _rosetta; }

layout_mamba() {
  local ACTIVATE="${HOME}/mambaforge/bin/activate"

  if [ -n "$1" ]; then
    # Explicit environment name from layout command.
    local env_name="$1"
    source $ACTIVATE ${env_name}
  # elif (grep -q name: environment.yml); then
  #   # Detect environment name from `environment.yml` file in `.envrc` directory
  #   source $ACTIVATE `grep name: environment.yml | sed -e 's/name: //' | cut -d "'" -f 2 | cut -d '"' -f 2`
  else
    (>&2 echo No environment specified);
    exit 1;
  fi;
}

# layout_mamba() { _mamba $@; }
