# Docs: https://github.com/crate-ci/typos

# # Identifiers vs. Words: https://github.com/crate-ci/typos/blob/master/docs/design.md#identifiers-and-words

[default.extend-words]
# Don't correct "iterm" or "iTerm"
iterm = "iterm"

[files]
extend-exclude = [
  ".typos.toml",
  "*.sops.yaml",
  "*.terminal",
  "macos_*_settings.sh"
]
