---
version: "3"

includes:
  git:
    taskfile: "./dotfiles/task/taskfiles/GitTasks.yaml"
    # internal: true
    aliases: [g]
  pipx:
    taskfile: "./dotfiles/task/taskfiles/PipxTasks.yaml"
    # internal: true
  zsh:
    taskfile: "./dotfiles/task/taskfiles/ZshTasks.yaml"
    # internal: true
    aliases: [z]

  sysconfig:
    taskfile: "./dotfiles/task/taskfiles/setup/SysconfigTasks.yaml"
    internal: true

# env:
#   KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

vars:
  SYS_CONFIG:
    sh: 'echo "$SYS_CONFIG"'
  CODE_DIR:
    sh: 'echo "$CODE_DIR"'
  TASK_SCRIPTS: "{{.SYS_CONFIG}}/dotfiles/task/scripts"

tasks:
  default:
    silent: true
    cmds:
      - task -l
#   upgrade:
#     desc: Upgrade Nix packages
#     silent: true
#     cmds:
#       - nix-env -u

#   switch:
#     desc: Switch to the new configuration
#     silent: true
#     cmds:
#       - home-manager switch

#   bootstrap:
#     desc: Bootstrap the home-manager configuration
#     silent: true
#     cmds:
#       - curl -L https://nixos.org/nix/install | sh
#       # TODO: if $(uname_os)
#       - source $HOME/.nix-profile/etc/profile.d/nix.sh
#       - export NIX_PATH=${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels
#       - nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
#       - task: update
#       - nix-shell '<home-manager>' -A install
#       - task: switch
#       - echo "$HOME/.nix-profile/bin/zsh" | sudo tee -a /etc/shells
#       - chsh -s $HOME/.nix-profile/bin/zsh
