---
version: "3"

includes:
  git:
    taskfile: "./GitTasks.yaml"
    internal: true

vars:
  SYS_CONFIG:
    sh: 'echo "$SYS_CONFIG"'
  BIN_DIR: "/usr/local/bin"
  CODE_DIR:
    sh: 'echo "$CODE_DIR"'

tasks:
  # default:
  #   silent: true
  #   cmds:
  #     - ...

  install:
    desc: Install mambaforge
    silent: true
    cmds:
      - curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
      - bash Mambaforge-$(uname)-$(uname -m).sh -b -f -p $HOME/mambaforge
      - rm Mambaforge-$(uname)-$(uname -m).sh

  env create:
    desc: Create a new conda environment (prompted)
    silent: true
    cmds:
      - conda_env_create

  env create flags:
    desc: Create a new conda environment (cli flags)
    summary: |
      Create a new conda environment with optional Python version and packages or from an environment.yaml file
      Usage: conda_env_create -n <env_name> [-p <python_version>] [-l <package list>] | [-r <environment_yaml>]
      Note: <package list> should be quoted and space-delimited or comma delimited
    silent: true
    cmds:
      - conda_env_create_flags
